// Type declaration for the virtual module generated by vite-plugin-bg-images
declare module 'virtual:bg-images' {
  /** Absolute-from-root URL paths to every image in /public/assets/projects/background/ */
  export const bgImages: string[]
}
